version: '3.3'
services:
  # ubuntu:
  #   platform: linux/x86_64
  #   build: ./
  #   restart: always
  #   volumes:
  #     - .:/root/Lab1

  #   depends_on:
  #     - db

  #   stdin_open: true
  #   tty: true

  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass1234'
      MYSQL_ROOT_PASSWORD: 'pass1234'
    ports:
      - '3307:3306'
    expose:
      - '3307'

    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: